In [1]:
import pandas as pd
intent = pd.read_csv('intent.csv')
persona = pd.read_csv('persona.csv')
subject = pd.read_csv('subject.csv')
template = pd.read_csv('template.csv')

In [3]:
template = template[:5]

In [2]:
import pandas as pd
import numpy as np
from itertools import product

# Create a mapping of dimension names to dataframes
dimension_dfs = {
    'subject': subject,
    'intent': intent,
    'persona': persona
}

def combine_dimensions(row):
    dimensions = row['keyword_template'].split(',')
    language = row['language']
    combinations = []

    for dimension in dimensions:
        if dimension in dimension_dfs:
            combinations.append(dimension_dfs[dimension].loc[dimension_dfs[dimension]['language'] == language, f'{dimension}_localised'].values.tolist())
        else:
            combinations.append([dimension])

    # Create all possible combinations
    combinations = list(product(*combinations))
    combinations = [' '.join(combination) for combination in combinations]

    return pd.Series(combinations)

# # Apply combine_dimensions function to each row in template
# template['combinations'] = template.apply(combine_dimensions, axis=1)

# # Explode combinations into separate rows
# template = template.explode('combinations')

# # Merge template with campaign_template_df
# merged_df = pd.merge(template, campaign_template_df, on='market_id')

# # Function to handle campaign combinations
# def campaign_combinations(row):
#     campaign_template = row['campaign_template'].split(',')
#     replacements = {
#         'market_id': str(row['market_id']),
#         'language': row['language']
#         # Add more replacements as needed
#     }

#     # Replace elements of the campaign template as needed
#     campaign_template = [replacements.get(item, item) for item in campaign_template]

#     return ' '.join(campaign_template)

# # Apply campaign_combinations function to each row in merged_df
# merged_df['campaign_combination'] = merged_df.apply(campaign_combinations, axis=1)

# # Final output dataframe
# final_df = merged_df[['language', 'keyword_template', 'market_id', 'campaign_template', 'combinations', 'campaign_combination']]

In [4]:
# template['combinations'] = 
template.apply(combine_dimensions, axis=1)

,0,1,2,3,4,5,6,7,8,9,...,3702,3703,3704,3705,3706,3707,3708,3709,3710,3711
0,teacher Arabic,teacher Bengali,teacher Croatian,teacher Czech,teacher English,teacher French,teacher Icelandic,teacher Irish,teacher Khmer,teacher Mandarin,...,TOPIK Hebrew,TOPIK Latin,TOPIK Polish,TOPIK Spanish,TOPIK Hungarian,TOPIK Sanskrit,TOPIK Math,TOPIK Chemistry,TOPIK Russian,TOPIK Slovak
1,Arabic teacher,Arabic tutor,Arabic speaker,Arabic partner,Arabic class,Arabic school,Arabic CNAVT,Arabic NT2,Arabic ACT,Arabic BEC,...,Slovak DEPLE,Slovak speak,Slovak lesson,Slovak CAEL,Slovak DALF,Slovak OSD,Slovak National,Slovak CILS,Slovak JLPT,Slovak TOPIK
2,teacher Arabic,teacher Bengali,teacher Croatian,teacher Czech,teacher English,teacher French,teacher Icelandic,teacher Irish,teacher Khmer,teacher Mandarin,...,TOPIK Hebrew,TOPIK Latin,TOPIK Polish,TOPIK Spanish,TOPIK Hungarian,TOPIK Sanskrit,TOPIK Math,TOPIK Chemistry,TOPIK Russian,TOPIK Slovak
3,Arabic teacher,Arabic tutor,Arabic speaker,Arabic partner,Arabic class,Arabic school,Arabic CNAVT,Arabic NT2,Arabic ACT,Arabic BEC,...,Slovak DEPLE,Slovak speak,Slovak lesson,Slovak CAEL,Slovak DALF,Slovak OSD,Slovak National,Slovak CILS,Slovak JLPT,Slovak TOPIK
4,Arabic teacher,Arabic tutor,Arabic speaker,Arabic partner,Arabic class,Arabic school,Arabic CNAVT,Arabic NT2,Arabic ACT,Arabic BEC,...,Slovak DEPLE,Slovak speak,Slovak lesson,Slovak CAEL,Slovak DALF,Slovak OSD,Slovak National,Slovak CILS,Slovak JLPT,Slovak TOPIK

In [8]:
template.merge(intent, how='inner', on='intent_localised_id')

,unique_keyword_id,intent_localised_id,keyword_template,language_x,intent_localised,language_y
0,5137f7e3aaa9d54f24d67913786ce4ba,340cd1dcf5d3871fa2584362194cc4fe,"intent,subject",eng,NT2,eng
1,5137f7e3aaa9d54f24d67913786ce4ba,340cd1dcf5d3871fa2584362194cc4fe,"intent,subject",eng,NT2,ita
2,5137f7e3aaa9d54f24d67913786ce4ba,340cd1dcf5d3871fa2584362194cc4fe,"intent,subject",eng,NT2,ara
3,5137f7e3aaa9d54f24d67913786ce4ba,340cd1dcf5d3871fa2584362194cc4fe,"intent,subject",eng,NT2,por
4,5137f7e3aaa9d54f24d67913786ce4ba,340cd1dcf5d3871fa2584362194cc4fe,"intent,subject",eng,NT2,fre
...,...,...,...,...,...,...
105,8ef49bdea5131365eb2ecee679824819,5a753229efb8128b16b50c38708c6638,"subject,intent",eng,CAEL,chi
106,8ef49bdea5131365eb2ecee679824819,5a753229efb8128b16b50c38708c6638,"subject,intent",eng,CAEL,tha
107,8ef49bdea5131365eb2ecee679824819,5a753229efb8128b16b50c38708c6638,"subject,intent",eng,CAEL,kor
108,8ef49bdea5131365eb2ecee679824819,5a753229efb8128b16b50c38708c6638,"subject,intent",eng,CAEL,tur
109,8ef49bdea5131365eb2ecee679824819,5a753229efb8128b16b50c38708c6638,"subject,intent",eng,CAEL,rum

In [7]:
len(intent)

1549